# Generated by Django 4.2.10 on 2024-02-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_code_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='6306811162:AAHDK967902pWwC1iBgJBHM5f0J2oLLqxdA', verbose_name='Токен телеграмма'),
        ),
    ]
