# Generated by Django 4.2.10 on 2024-02-08 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150, verbose_name='Действие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
        migrations.CreateModel(
            name='Reflex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=100, verbose_name='Место действия')),
                ('data', models.DateTimeField(verbose_name='Время действия')),
                ('periodicity', models.CharField(choices=[('week', 'Раз в неделю'), ('every_day', 'Каждый день')], default='every_day', verbose_name='Переодичность')),
                ('is_publicity', models.BooleanField(verbose_name='признак публикации')),
                ('fee', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознагрождение')),
                ('action', models.CharField(max_length=150, verbose_name='Действие')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='Время на выполение')),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit', verbose_name='Привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рефлекс',
                'verbose_name_plural': 'Рефлексы',
            },
        ),
    ]
