# Generated by Django 4.2.10 on 2024-02-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_reflex_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflex',
            name='nice_reflex',
            field=models.BooleanField(default=False, verbose_name='признак привычки'),
        ),
    ]
